name: CI
on:
  pull_request:
    paths-ignore:
    - '**/*.md'
  push:
    branches:
    - main
  schedule:
  - cron: 0 3 * * *

jobs:
  tests:
    strategy:
      matrix:
        os:
        - ubuntu-latest
        python-version:
        - '3.8'
        - '3.9'
        - '3.10'
        - '3.11'
        include:
          # only test oldest and most recent Python on other platforms
        - os: macos-latest
          python-version: '3.8'
        - os: macos-latest
          python-version: '3.11'
        - os: windows-latest
          python-version: '3.8'
        - os: windows-latest
          python-version: '3.11'
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout Source
      uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Setup package
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install .[dev]
    - name: Run test suite
      run: pytest
    - uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: test_results
        path: test_results/

  minimal-dependencies:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Source
      uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    - name: Setup package
      run: |
        python -m pip install --upgrade pip
        python -m pip install tomli tomli_w
        python scripts/hardpin_minimal_dependencies.py
        python -m pip install -e .[dev]
    - name: Run test suite
      run: pytest

  image_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Setup package
      run: python3 -m pip install ".[dev]"

    - name: Run image tests
      run: |
        pytest -vvv --mpl --mpl-generate-summary=html --mpl-results-path=mpl_results

    - name: Upload pytest-mpl report
      uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: image_tests_report
        path: mpl_results/*
